routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SitemapXmlController;

// Adding redirects for old links from previous website
Route::get('/management/', function() { return Redirect::to('/resources/management', 301); });
Route::get('/community/', function() { return Redirect::to('/resources/community', 301); });
Route::get('/savings/', function() { return Redirect::to('/personal-banking/savings', 301); });
Route::get('/commercial-lending/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/real-estate-construction', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/acquisition-expansion/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/machinery-equipment/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/what-to-bring-with-you/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/commercial/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/sba-preferred-lender', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/loc/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/business-accounts/', function() { return Redirect::to('/business-banking/business-services', 301); });
Route::get('/business-services/', function() { return Redirect::to('/business-banking/business-services', 301); });
Route::get('/wealth-management/', function() { return Redirect::to('financial-planning/investment-services', 301); });
Route::get('/mortgage/', function() { return Redirect::to('/lending/mortgages', 301); });
Route::get('/securlock', function() { return Redirect::to('/resources/securlock', 301); });
Route::get('/iras', function() { return Redirect::to('personal-banking/iras-invest-in-your-future', 301); });
Route::get('/checking', function() { return Redirect::to('personal-banking/checking', 301); });
Route::get('/locations', function() { return Redirect::to('contact-us', 301); });
Route::get('/careers', function() { return Redirect::to('resources/careers', 301); });
Route::get('/e-banking', function() { return Redirect::to('personal-banking/e-banking', 301); });
Route::get('/mobile-banking', function() { return Redirect::to('personal-banking/e-banking', 301); });
Route::get('/mortgage-faqs', function() { return Redirect::to('lending/mortgage-faqs', 301); });
Route::get('/deposit-rates', function() { return Redirect::to('personal-banking/deposit-rates', 301); });
Route::get('/consumer-loans', function() { return Redirect::to('lending/consumer-loan', 301); });
Route::get('/construction-loan', function() { return Redirect::to('lending/construction-loan', 301); });
Route::get('/remote-banking', function() { return Redirect::to('personal-banking/remote-banking', 301); });
Route::get('/financial-literacy', function() { return Redirect::to('resources/financial-literacy', 301); });
Route::get('/life-insurance', function() { return Redirect::to('financial-planning/life-insurance', 301); });
Route::get('/fdic-reg-privacy', function() { return Redirect::to('resources/fdicregsprivacy', 301); });
Route::get('/the-bank-of-benningtons-privacy-policy', function() { return Redirect::to('resources/fdicregsprivacy', 301); });
Route::get('/home-equity-loan', function() { return Redirect::to('lending/home-equity-loan', 301); });
Route::get('/how-to-switch', function() { return Redirect::to('resources/how-to-switch', 301); });
Route::get('/e-banking-best-practices', function() { return Redirect::to('resources/e-banking-best-practices', 301); });
Route::get('/keep-your-information-safe', function() { return Redirect::to('resources/e-banking-best-practices', 301); });
Route::get('/why-choose-the-bank-of-bennington', function() { return Redirect::to('resources/why-choose-the-bank-of-bennington', 301); });
Route::get('/about-us', function() { return Redirect::to('resources/why-choose-the-bank-of-bennington', 301); });
Route::get('/rates/deposit-rates', function() { return Redirect::to('personal-banking/deposit-rates', 301); });
Route::get('/people-pay', function() { return Redirect::to('personal-banking/remote-banking', 301); });
Route::get('/kids-savers/', function() { return Redirect::to('personal-banking/savings', 301); });

//Route::get('sitemap.xml', [SitemapXmlController::class, 'generate']);

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('can:admin_area')->group(function() {
    Route::resource('announcements', 'AnnouncementsController');
    Route::resource('home-slider', 'HomeSliderController');
    Route::post('home-slider/sort', 'HomeSliderController@sort');

    Route::resource('login-links', 'LoginLinksController');
    Route::post('login-links/sort', 'LoginLinksController@sort');

    Route::resource('home-cards', 'HomeCardsController');
    Route::post('home-cards/sort', 'HomeCardsController@sort');

    Route::resource('footer-links', 'FooterLinksController');
    Route::post('footer-links/sort', 'FooterLinksController@sort');

    Route::resource('footer', 'FooterController');

    Route::resource('speedbump', 'SpeedBumpController');
});

app/Models/HomeCard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HomeCard extends Model
{
    protected $fillable = ['title', 'content', 'button_text', 'button_url', 'active', 'image', 'alt_text'];
    protected $appends = ['photo'];

    public function getPhotoAttribute() {
        return $this->image ? $this->image : '/img/img.jpg';
    }
}

app/Http/Controllers/Admin/HomeCardsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\HomeCard;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Intervention\Image\ImageManagerStatic as Image;


class HomeCardsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cards = HomeCard::orderBy('order', 'asc')->get();
        return response()->view('admin.home-cards.list',['cards' => $cards]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return response()->view('admin.home-cards.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('admin.home-cards.create')->with('error', $validator->errors()->first());
        }

        $data['active'] = isset($data['active']) ? true : false;
        try {
            $card = HomeCard::create($data);
            if(isset($data['image'])) $this->storeCardImage($card,$request);
            $card->save();

            return redirect()->route('admin.home-cards.edit', $card->id)->with('success', 'Home Card Created');
        } catch (\Exception $ex) {
            report($ex);
            return redirect()->route('admin.home-cards.create')->with('error', $ex->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $card = HomeCard::find($id);
        return response()->view('admin.home-cards.edit', ['card' => $card]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('admin.home-cards.edit', $id)->with('error', $validator->errors()->first());
        }

        $data['active'] = isset($data['active']) ? true : false;
        try {
            $card = HomeCard::find($id);
            $card->fill($data);
            if(isset($data['image'])) $this->storeCardImage($card,$request);
            $card->save();

            return redirect()->route('admin.home-cards.edit', $card->id)->with('success', 'Home Card Updated');
        } catch (\Exception $ex) {
            report($ex);
            return redirect()->route('admin.home-cards.edit', $card->id)->with('error', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            # Validation
            $this->validate($request, [
                'confirm_delete' => 'required|in:delete,Delete,DELETE'
            ]);
            $slide = HomeCard::find($id);
            $slide->delete();
            return redirect()->route('admin.home-cards.index')->with('success', 'Home Card Deleted');
        } catch (\Exception $ex) {
            return redirect()->route('admin.home-cards.index')->with('error', $ex->getMessage());
        }
    }

    private function storeCardImage(HomeCard $card, Request $request){
        if($request->hasFile('image')){
            $filename = $card->id.'_'.
                str_slug($card->title).
                '.'.$request->file('image')->getClientOriginalExtension();
            $card->image = $this->fileUpload($request, $filename,'app/public/cards/');
        }
    }

    /**
     * Stores file in storage
     * @param  \Illuminate\Http\Request  $request
     * @return string|null uploaded file path
     */
    public function fileUpload($request, $name, $directory) {
        $image = Image::make($request->file('image')->getRealPath());
        $image->fit(430,240)->save(storage_path($directory) . $name);
        return '/storage/cards/' . $name;
    }

    /**
     * Updates the sorting order of the homepage cards
     * @param  \Illuminate\Http\Request  $request
     * @return object
     */
    public function sort(Request $request) {
        if($request->get('cards')) {
            $cards = $request->get('cards');
            foreach($cards as $index => $card) {
                $homeCard = HomeCard::find($card['id']);
                $homeCard->order = $index;
                $homeCard->save();
            }
        }
        return response()->json(['success' => true]);
    }
}

resources/views/admin/home-cards/create.blade.php
@extends('larafish::layouts.admin.master')

@section('title', 'Home Card Creation')

@section('content')
    <section class="container-bank-xl mx-auto box has-margin-top-size-3 has-margin-bottom-size-3">
        <header class="level">
            <div class="level-left">
                <div class="level-item">
                    <h1 class="is-size-1">Home Card Creation</h1>
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    <a href="{{ URL::route('admin.home-cards.index',[],false) }}" title="View All Home Cards" class="button is-primary is-family-primary"><b-icon icon="bookmark-multiple"></b-icon><span>View All Home Cards</span></a>
                </div>
            </div>
        </header>
        <form enctype="multipart/form-data" action="{{ URL::route('admin.home-cards.store') }}" method="POST">
            @csrf
            <div class="field">
                <label for="title" class="label">Title</label>
                <input required type="text" placeholder="Title" name="title" class="input">
            </div>
            <div class="field">
                <label for="content" class="label">Content</label>
                <textarea name="content" id="content" class="textarea" placeholder="Content goes here..."></textarea>
            </div>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label for="button_text" class="label">Button Text</label>
                        <input required type="text" placeholder="Button Text" name="button_text" class="input">
                    </div>
                </div>
                <div class="column">
                    <div class="field">
                        <label for="button_url" class="label">Button URL</label>
                        <input required type="text" placeholder="Button URL" name="button_url" class="input">
                    </div>
                </div>
            </div>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label for="image" class="label">Card Image (430x240)</label>
                        <input type="file" accept=".jpg, .jpeg .png" name="image" />
                    </div>
                </div>
            </div>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label for="Image Alt Text" class="label">Card Image Alt Text</label>
                        <input type="text" name="alt_text" class="input">
                    </div>
                </div>
                <div class="column"></div>
            </div>
            <div class="field">
                <label for="active" class="label">Visible</label>
                <label for="active">
                    <input id="active" type="checkbox" name="active">
                    Yes
                </label>
            </div>

            <hr>

            <div class="field">
                <div class="control">
                    <button type="submit" class="button is-primary">Create</button>
                </div>
            </div>
        </form>
    </section>
@endsection

resources/views/admin/home-cards/edit.blade.php
@extends('larafish::layouts.admin.master')

@section('title', 'Home Card Editing')

@section('content')
    <section class="container-bank-xl mx-auto box has-margin-top-size-3 has-margin-bottom-size-3">
        <header class="level">
            <div class="level-left">
                <div class="level-item">
                    <h1 class="is-size-1">Home Card Editing</h1>
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    <a href="{{ URL::route('admin.home-cards.index',[],false) }}" title="View All Home Cards" class="button is-primary is-family-primary"><b-icon icon="bookmark-multiple"></b-icon><span>View All Home Cards</span></a>
                </div>
            </div>
        </header>
        <div class="columns">
            <div class="column">
                <form action="{{ URL::route('admin.home-cards.update', $card->id, false) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('patch')
                    <div class="field">
                        <label for="title" class="label">Title</label>
                        <input required type="text" placeholder="Title" name="title" class="input" value="{{$card->title}}">
                    </div>
                    <div class="field">
                        <label for="content" class="label">Content</label>
                        <textarea name="content" id="content" class="textarea" placeholder="Content goes here...">{{$card->content}}</textarea>
                    </div>
                    <div class="columns">
                        <div class="column">
                            <div class="field">
                                <label for="button_text" class="label">Button Text</label>
                                <input required type="text" placeholder="Button Text" value="{{$card->button_text}}" name="button_text" class="input">
                            </div>
                        </div>
                        <div class="column">
                            <div class="field">
                                <label for="button_url" class="label">Button URL</label>
                                <input required type="text" placeholder="Button URL" value="{{$card->button_url}}" name="button_url" class="input">
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column">
                            <div class="field">
                                <label for="image" class="label">Card Image (430x240)</label>
                                <input type="file" accept=".jpg, .jpeg .png" name="image" />
                                @if($card->photo)
                                    <img class="mt-4" src="{{$card->photo}}" />
                                @endif
                            </div>
                        </div>
                        <div class="column">
                            <div class="field">
                                <label for="Image Alt Text" class="label">Card Image Alt Text</label>
                                <input type="text" name="alt_text" class="input" value="{{$card->alt_text}}">
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <label for="active" class="label">Visible</label>
                        <label for="active">
                            <input id="active" type="checkbox" name="active" {{$card->active ? 'checked="checked"' : ''}}>
                            Yes
                        </label>
                    </div>

                    <hr>

                    <div class="field">
                        <div class="control">
                            <button type="submit" class="button is-primary">Update</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="column is-one-third">
                <form method="post" action="{{URL::route('admin.home-cards.destroy',$card->id)}}" class="form box is-danger">
                    <div class="field">
                        <label class="label has-text-danger" for="confirm_delete">Delete Home Card</label>
                        <p class="control">
                            <input class="input" type="text" id="confirm_delete" name="confirm_delete" placeholder="DELETE" required>
                        </p>
                        <p class="help has-text-danger">Type "DELETE" to confirm deletion.</p>
                    </div>
                    <div class="control">
                        <button type="submit" class="button is-danger">Delete Home Card</button>
                    </div>
                    @method('DELETE')
                    @csrf
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/home-cards/list.blade.php
@extends('larafish::layouts.admin.master')

@section('title', 'Home Cards Manager')

@section('content')
    <section class="container-bank-xl mx-auto box has-margin-top-size-3">
        <header>
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <h1 class="is-size-1">Home Cards Manager</h1>
                    </div>
                    <p>(Drag rows to sort priority)</p>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <a href="{{route('admin.home-cards.create')}}" class="button is-primary">
                            <span class="icon"><i class="mdi mdi-bookmark-plus"></i></span>
                            <span>New Home Card</span>
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <home-card-table :cards='@json($cards)' />
    </section>
@endsection