routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SitemapXmlController;

// Adding redirects for old links from previous website
Route::get('/management/', function() { return Redirect::to('/resources/management', 301); });
Route::get('/community/', function() { return Redirect::to('/resources/community', 301); });
Route::get('/savings/', function() { return Redirect::to('/personal-banking/savings', 301); });
Route::get('/commercial-lending/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/real-estate-construction', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/acquisition-expansion/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/machinery-equipment/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/what-to-bring-with-you/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/commercial/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/sba-preferred-lender', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/loc/', function() { return Redirect::to('/business-banking/commercial-lending', 301); });
Route::get('/business-accounts/', function() { return Redirect::to('/business-banking/business-services', 301); });
Route::get('/business-services/', function() { return Redirect::to('/business-banking/business-services', 301); });
Route::get('/wealth-management/', function() { return Redirect::to('financial-planning/investment-services', 301); });
Route::get('/mortgage/', function() { return Redirect::to('/lending/mortgages', 301); });
Route::get('/securlock', function() { return Redirect::to('/resources/securlock', 301); });
Route::get('/iras', function() { return Redirect::to('personal-banking/iras-invest-in-your-future', 301); });
Route::get('/checking', function() { return Redirect::to('personal-banking/checking', 301); });
Route::get('/locations', function() { return Redirect::to('contact-us', 301); });
Route::get('/careers', function() { return Redirect::to('resources/careers', 301); });
Route::get('/e-banking', function() { return Redirect::to('personal-banking/e-banking', 301); });
Route::get('/mobile-banking', function() { return Redirect::to('personal-banking/e-banking', 301); });
Route::get('/mortgage-faqs', function() { return Redirect::to('lending/mortgage-faqs', 301); });
Route::get('/deposit-rates', function() { return Redirect::to('personal-banking/deposit-rates', 301); });
Route::get('/consumer-loans', function() { return Redirect::to('lending/consumer-loan', 301); });
Route::get('/construction-loan', function() { return Redirect::to('lending/construction-loan', 301); });
Route::get('/remote-banking', function() { return Redirect::to('personal-banking/remote-banking', 301); });
Route::get('/financial-literacy', function() { return Redirect::to('resources/financial-literacy', 301); });
Route::get('/life-insurance', function() { return Redirect::to('financial-planning/life-insurance', 301); });
Route::get('/fdic-reg-privacy', function() { return Redirect::to('resources/fdicregsprivacy', 301); });
Route::get('/the-bank-of-benningtons-privacy-policy', function() { return Redirect::to('resources/fdicregsprivacy', 301); });
Route::get('/home-equity-loan', function() { return Redirect::to('lending/home-equity-loan', 301); });
Route::get('/how-to-switch', function() { return Redirect::to('resources/how-to-switch', 301); });
Route::get('/e-banking-best-practices', function() { return Redirect::to('resources/e-banking-best-practices', 301); });
Route::get('/keep-your-information-safe', function() { return Redirect::to('resources/e-banking-best-practices', 301); });
Route::get('/why-choose-the-bank-of-bennington', function() { return Redirect::to('resources/why-choose-the-bank-of-bennington', 301); });
Route::get('/about-us', function() { return Redirect::to('resources/why-choose-the-bank-of-bennington', 301); });
Route::get('/rates/deposit-rates', function() { return Redirect::to('personal-banking/deposit-rates', 301); });
Route::get('/people-pay', function() { return Redirect::to('personal-banking/remote-banking', 301); });
Route::get('/kids-savers/', function() { return Redirect::to('personal-banking/savings', 301); });

//Route::get('sitemap.xml', [SitemapXmlController::class, 'generate']);

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('can:admin_area')->group(function() {
    Route::resource('announcements', 'AnnouncementsController');
    Route::resource('home-slider', 'HomeSliderController');
    Route::post('home-slider/sort', 'HomeSliderController@sort');

    Route::resource('login-links', 'LoginLinksController');
    Route::post('login-links/sort', 'LoginLinksController@sort');

    Route::resource('home-cards', 'HomeCardsController');
    Route::post('home-cards/sort', 'HomeCardsController@sort');

    Route::resource('footer-links', 'FooterLinksController');
    Route::post('footer-links/sort', 'FooterLinksController@sort');

    Route::resource('footer', 'FooterController');

    Route::resource('speedbump', 'SpeedBumpController');
});

app/Models/HomeSlider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HomeSlider extends Model
{
    protected $table = 'home_slides';
    protected $fillable = ['title','content','button_url','button_text','image','active', 'alt_text'];
    protected $appends = ['photo'];

    public function getPhotoAttribute() {
        return $this->image ? $this->image : '/img/slider.jpg';
    }
}

app/Http/Controllers/Admin/HomeSliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\HomeSlider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class HomeSliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slides = HomeSlider::orderBy('order', 'asc')->get();
        return response()->view('admin.home-slider.list',['slides' => $slides]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return response()->view('admin.home-slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('admin.home-slider.create')->with('error', $validator->errors()->first());
        }

        $data['active'] = isset($data['active']) ? true : false;
        try {
            $slide = HomeSlider::create($data);
            if(isset($data['image'])) $this->storeSlideImage($slide,$request);
            $slide->save();

            return redirect()->route('admin.home-slider.edit', $slide->id)->with('success', 'Slide Created');
        } catch (\Exception $ex) {
            report($ex);
            return redirect()->route('admin.home-slider.create')->with('error', $ex->getMessage());
        }
    }

    private function storeSlideImage(HomeSlider $slide,Request $request){
        if($request->hasFile('image')){
            $filename = $slide->id.'_'.
                str_slug($slide->title).
                '.'.$request->file('image')->getClientOriginalExtension();
            $slide->image = $this->fileUpload($request, $filename,'slides');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slide = HomeSlider::find($id);
        return response()->view('admin.home-slider.edit', ['slide' => $slide]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'title' => 'required',
            'content' => 'required',
        ]);

        if ($validator->fails()) {
            return redirect()->route('admin.home-slider.edit', $id)->with('error', $validator->errors()->first());
        }

        try {
            $data['active'] = isset($data['active']) ? true : false;
            $slide = HomeSlider::find($id);
            $slide->fill($data);
            if(isset($data['image'])) $this->storeSlideImage($slide,$request);
            $slide->save();

            return redirect()->route('admin.home-slider.edit', $slide->id)->with('success', 'Slide Updated');
        } catch (\Exception $ex) {
            report($ex);
            return redirect()->route('admin.home-slider.edit', $slide->id)->with('error', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            # Validation
            $this->validate($request, [
                'confirm_delete' => 'required|in:delete,Delete,DELETE'
            ]);
            $slide = HomeSlider::find($id);
            $slide->delete();
            return redirect()->route('admin.home-slider.index')->with('success', 'Slider Deleted');
        } catch (\Exception $ex) {
            return redirect()->route('admin.home-slider.index')->with('error', $ex->getMessage());
        }
    }

    /**
     * Stores file in storage
     * @param  \Illuminate\Http\Request  $request
     * @return string|null uploaded file path
     */
    public function fileUpload($request, $name, $directory) {
        $path = $request->file('image')->storeAs($directory, $name ,'public');
        return '/storage/' . $path;
    }

    /**
     * Updates the sorting order of the homepage slider
     * @param  \Illuminate\Http\Request  $request
     * @return object
     */
    public function sort(Request $request) {
        if($request->get('slides')) {
            $slides = $request->get('slides');
            foreach($slides as $index => $slide) {
                $slide = HomeSlider::find($slide['id']);
                $slide->order = $index;
                $slide->save();
            }
        }
        return response()->json(['success' => true]);
    }
}

resources/views/admin/home-slider/create.blade.php
@extends('larafish::layouts.admin.master')

@section('title', 'Slide Creation')

@section('content')
    <section class="container-bank-xl mx-auto box has-margin-top-size-3 has-margin-bottom-size-3">
        <header class="level">
            <div class="level-left">
                <div class="level-item">
                    <h1 class="is-size-1">Slide Creation</h1>
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    <a href="{{ URL::route('admin.home-slider.index',[],false) }}" title="View All Slides" class="button is-primary is-family-primary"><b-icon icon="bookmark-multiple"></b-icon><span>View All Slides</span></a>
                </div>
            </div>
        </header>
        <edit-slider-form :page="'Create'"
              method="post"
              enctype="multipart/form-data"
              action="{{ URL::route('admin.home-slider.store',[],false) }}"
              @if($errors->isNotEmpty()) :errors='@json($errors->getMessages())' @endif>
            @csrf
        </edit-slider-form>
    </section>
@endsection

resources/views/admin/home-slider/edit.blade.php
@extends('larafish::layouts.admin.master')

@section('title', 'Slide Editing')

@section('content')
    <section class="container-bank-xl mx-auto box has-margin-top-size-3 has-margin-bottom-size-3 home-slider">
        <header class="level">
            <div class="level-left">
                <div class="level-item">
                    <h1 class="is-size-1">Slide Editing</h1>
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    <a href="{{ URL::route('admin.home-slider.index',[],false) }}" title="View All Slides" class="button is-primary is-family-primary"><b-icon icon="bookmark-multiple"></b-icon><span>View All Slides</span></a>
                </div>
            </div>
        </header>
        <div class="columns">
            <div class="column">
                <edit-slider-form :page="'Update'"
                      method="post"
                      enctype="multipart/form-data"
                      action="{{ URL::route('admin.home-slider.update',$slide->id,false) }}"
                      :slide='@json($slide)'
                      @if($errors->isNotEmpty()) :errors='@json($errors->getMessages())' @endif>
                      @csrf
                      @method('patch')
                </edit-slider-form>
            </div>

            <div class="column is-one-third">
                <form method="post" action="{{URL::route('admin.home-slider.destroy',$slide->id)}}" class="form box is-danger">
                    <div class="field">
                        <label class="label has-text-danger" for="confirm_delete">Delete Slide</label>
                        <p class="control">
                            <input class="input" type="text" id="confirm_delete" name="confirm_delete" placeholder="DELETE" required>
                        </p>
                        <p class="help has-text-danger">Type "DELETE" to confirm deletion.</p>
                    </div>
                    <div class="control">
                        <button type="submit" class="button is-danger">Delete Slide</button>
                    </div>
                    @method('DELETE')
                    @csrf
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/home-slider/list.blade.php
@extends('larafish::layouts.admin.master')

@section('title', 'Home Slider Manager')

@section('content')
    <section class="container-bank-xl mx-auto box has-margin-top-size-3">
        <header>
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <h1 class="is-size-1">Home Slider Manager</h1>
                    </div>
                    <p>(Drag rows to sort priority)</p>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <a href="{{route('admin.home-slider.create')}}" class="button is-primary">
                            <span class="icon"><i class="mdi mdi-bookmark-plus"></i></span>
                            <span>New Slide</span>
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <home-slider-table :slides='@json($slides)' />
    </section>
@endsection